### PR TITLE
Alert converted to toast

### PR DESCRIPTION
**Pull request by AmeyaJain-25**
Issue: #109 
The html alert is converted to material UI snackbar.
Here are the screenshot for it.

Screenshot from 2021-04-10 22-45-00
Screenshot from 2021-04-10 22-45-30

### CODE REVIEW

**Comment by Vishv07** [comment]
@AmeyaJain-25 Alert could have done better in terms of UI. and what if we use Error message alert that we are using for code editor errors. @kothariji

**Comment by kothariji** [comment]
Great work @AmeyaJain-25, but according to the UI perspective, their alerts are not dissolving with the website UI, so instead of that we can use the traditional alerts which are there in SyntaxMeets for the copy room ID, and we can directly redirect the user to the homepage.

**Comment by kothariji** [comment]
> @AmeyaJain-25 Alert could have done better in terms of UI. and what if we use Error message alert that we are using for code editor errors. @kothariji

Yes exactly what I mean to say. @Vishv07 🙌

**Comment by AmeyaJain-25** [comment]
Yep Sure @Vishv07 @kothariji 
Great Idea.

Initially I thought that user have to been given a dialog for it.

I tried showing just the error and then redirect, but I was redirecting immediately and the notification is not able to see.
What I think now is,
I'll show the default error message and then after 1 sec or 2 sec delay, I'll redirect the page.
Would that be fine?

**Review by kothariji — APPROVED** [review]
@AmeyaJain-25 Thanks for the contributions 🚀  

Keep Contributing 🔥

**Pull request merged**
