### PR TITLE
Improve copy message UI

### PR DESCRIPTION
**Pull request by Priyankcoder**
**This PR fixes:**
- Copy message UI #44, [Here](https://imgur.com/a/bNEvwOl) is the updated UI gif.

**Related Details**
- I implemented this using the material-ui as it is used in the project and this is better than the UI suggested by me earlier.

### CODE REVIEW

**Review by kothariji — CHANGES_REQUESTED** [review]
Thank you @Priyankcoder for the PR.
This is really much better than the old browser alert. 🙌 

But there is a small suggestion, can we add the snack bar alert position to the bottom, as it is in the welcome alert/user left alert.
For eg - 
image

So that it maintains the same consistency.

Please let me know what you think about it 🔥

**Comment by Priyankcoder** [comment]
Yes, in fact, I considered that place earlier for consistency. But, I realized it is unnoticeable as the user focus lies around the copy button while clicking it. Watching an instant green tick with a message just after the button click is more satisfying from the user's perspective.
If you still think that the default place is better then do let me know I will do the changes.

**Comment by kothariji** [comment]
> Yes, in fact, I considered that place earlier for consistency. But, I realized it is unnoticeable as the user focus lies around the copy button while clicking it. Watching an instant green tick with a message just after the button click is more satisfying from the user's perspective.
> If you still think that the default place is better then do let me know I will do the changes.

Yes, that's also true, but for the time being, it would be better if you can add it to the default place, with **variant="filled"**, so that it maintains the UI consistency.

Happy Sunday!  🙌

**Review by kothariji — APPROVED** [review]
This looks perfect. 🚀

**Comment by Priyankcoder** [comment]
Yeah sure. Please, add the GSSOC21 label to this PR as PR with that label would be considered only for GSSOC21. Also, Is there any way to add labels to PR from my side?

**Comment by kothariji** [comment]
> Yeah sure. Please, add the GSSOC21 label to this PR as PR with that label would be considered only for GSSOC21. Also, Is there any way to add labels to PR from my side?

Done 🙌 .
No, only collaborators of the project can add labels to the PR

**Pull request merged**
