### PR TITLE
Changing RoomId copied message

### PR DESCRIPTION
**Pull request by Lavcodes**
Solves #93  

Changed message on copying RoomId to "Invite created ! Share with your friends and have a meet."

### CODE REVIEW

**Review by kothariji — APPROVED** [review]
LGTM 🚀

**Comment by kothariji** [comment]
@Lavcodes can you please remove the merge conflicts, so that we can merge the PR. 🙌

**Comment by Lavcodes** [comment]
I've tried resolving these conflicts could you review

**Comment by kothariji** [comment]
> I've tried resolving these conflicts could you review

@Lavcodes can you please uncommit the package-lock.json, cause its preventing me from merging(reason - merge conflcits)

**Comment by Lavcodes** [comment]
I've uncommitted those changes

**Review by kothariji — APPROVED** [review]
Thanks for your contributions @Lavcodes 🔥 

Keep Contributing 🙌 🚀

**Pull request merged**
