### PR TITLE
⚒️[Fix]: Improved UI

### PR DESCRIPTION
**Pull request by jainaayush01**
Issue #58

### CODE REVIEW

**Review by kothariji — COMMENTED** [review]
Thank you @jainaayush01 for creating the PR 🚀 
Can you please remove LanguageData.js and SyntaxEditor.js from this PR, so that I can merge this PR.

Thanks

**Review by kothariji — CHANGES_REQUESTED** [review]
@jainaayush01

**Review by kothariji — APPROVED** [review]
Great, so for now, we can have LanguageData, cause it's not affecting the Editor.

**Comment by jainaayush01** [comment]
Wait I have removed syntaxEditor.js by mistake.
I have done the necessary changes and just checking with the local development

**Review by kothariji — CHANGES_REQUESTED** [review]
Hi @jainaayush01, now to can't delete the file directly, If I'll merge this PR, SntaxEditor.js will be deleted from the original repo as well.

So instead of that what you can do is, create a new PR

**Comment by jainaayush01** [comment]
Now it is good to go

**Comment by kothariji** [comment]
> Wait I have removed syntaxEditor.js by mistake.
> I have done the necessary changes and just checking with the local development

Yes even I was like shocked for a sec 😆😆, no issues

**Review by kothariji — APPROVED** [review]
Thanks 🔥

**Comment by jainaayush01** [comment]
First PR Merged Woohoo!!
Thanks for your time

**Comment by kothariji** [comment]
> First PR to be Merged Woohoo!!
> Thanks for your time

Keep Contributing, open source is ❤️

**Pull request merged**
