### PR TITLE
feat: Enter Key will submit forms

### LINKED ISSUE #50: Enter Key should submit Forms
**Describe the solution you'd like**
For creating a room or joining a room, after filling in the necessary information, if the user presses Enter Key, it should automatically take us to the result page.

**Are you willing to contribute to this issue?** [Yes/No]
Yes

### PR DESCRIPTION
**Pull request by anhushree**
Fixes #50 
Using the `onKeyPress()` and `click()`, it will programmatically redirect the user to the required page on pressing Enter key

### CODE REVIEW

**Comment by Vishv07** [comment]
Works fine. @anhushree  But we gotta put a validation check on the name too. @kothariji

**Comment by anhushree** [comment]
maybe we have that as a separate issue?

**Review by Akash-Salvi — APPROVED** [review]
LGTM 🔥 👍

**Review by kothariji — CHANGES_REQUESTED** [review]
Hi @anhushree , finally to found a way out to make <kbd>Enter Key</kbd> work. Great work.

But as @Vishv07 mentioned, and I also feel  like, there are some bugs in this.

You can see the [Preview Link](https://syntaxmeets-git-fork-anhushree-enterkey-kothariji.vercel.app)

If I try to join a room, with a improper roomID ,  Then also on press of enter key, user is redirected on SyntaxRooms...which is incorrect.
Reference:- 
image

image

So we need strong validation in the home page. So I would request you to add those validations. And you can simply see when the button is enabled..then only a user can go to syntaxroom. This will definitely resolve the issue.

**Comment by anhushree** [comment]
Yes, I understood. I Will work on it. Sorry for the delay. @kothariji

**Comment by anhushree** [comment]
Basically, this room doesn't exist
When I enter the Room Id and trigger the mouse click, it redirects me to the respective page.
Hence I would suggest taking this up as an individual issue, cuz this has a different problem in its root and not just as a bug.

Images for reference (mouse click)

image

image
Preview: [https://syntaxmeets.vercel.app/](url)

**Comment by kothariji** [comment]
what you can try is
in your on Key Press function
```
onKeyPress={(ev) => {
                      if(ev.key === 'Enter') {
                        ev.preventDefault();
                        createRoomButton.current.click();
                      }
                    }}
```

you can add an if condition inside line 3 that
if disabledName || disabledRoomId is true...then don't click the button.
Hope it would work

**Comment by anhushree** [comment]
I understand the functionality you just explained, but I believe that it should be a part of another issue. The existing codebase has no validation when the create a room/join room buttons are pressed. The issue that I created talks only about implementing the same functionality as the button press when a user hits the enter button. It doesn't talk about the absence of validation in the codebase at all. I would be happy to work on validation, but I think it should be in a separate issue.

**Comment by kothariji** [comment]
> I understand the functionality you just explained, but I believe that it should be a part of another issue. The existing codebase has no validation when the create a room/join room buttons are pressed. The issue that I created talks only about implementing the same functionality as the button press when a user hits the enter button. It doesn't talk about the absence of validation in the codebase at all. I would be happy to work on validation, but I think it should be in a separate issue.

@anhushree the existing codebase has validations for name and room id. But actually, we can't push a code that has a bug to production. But no issues I had added validation check to your code. Feel free to check that 🙌 .

**Review by kothariji — APPROVED** [review]
Rest everything is working great. Thank you @anhushree for the contributions 🔥 
Keep contributing 🚀

**Pull request merged**
