### PR TITLE
added code share feature and image of code snippet

### PR DESCRIPTION
**Pull request by subhangi2731**
closes issue #74

### CODE REVIEW

**Comment by subhangi2731** [comment]
@kothariji please merge my pr

**Comment by subhangi2731** [comment]
@kothariji please merge my pr

**Comment by kothariji** [comment]
Hi @subhangi2731, I am facing this issue
image

**Comment by subhangi2731** [comment]
@kothariji ok let me check

**Comment by subhangi2731** [comment]
@kothariji  I am not getting any error, I am getting correct link, can I mention steps to reproduce the error

**Comment by subhangi2731** [comment]
@kothariji I have done and tested everything

**Comment by kothariji** [comment]
@subhangi2731 ok wait, I'll check again.

**Comment by kothariji** [comment]
Great @subhangi2731, it's working fine 🚀 
But the thing is, the link is not accessible properly. Its inside alert, which closes automatically.
So instead that can you please place the link somewhere else where it can be easily accessed.
For example 
image


Here we can create a modal, similar to the one which google meets have.
Where we can give the generated link of code snippet

**Comment by subhangi2731** [comment]
@kothariji for creating the modal this issue should be level 3 because then there are many things to be done and I have already done so much in this issue

**Comment by subhangi2731** [comment]
can u please assign level 3 to this @kothariji cause for the level 2 part I have already done that

**Comment by kothariji** [comment]
@subhangi2731 cool! I agree with you here.
So for this issue to be level3
1. Add a modal, in which there would be a link to the generated code snippet code.
2. Add some kind of a loader, as it is async/await request, so it may take a few seconds to generate, till that time there should be a loader in the screen.

On fulfilling all the above requirements, I will change the tags from Lvl2 to LVl3

**Comment by subhangi2731** [comment]
https://user-images.githubusercontent.com/53938490/120095773-60733800-c145-11eb-847a-b14b23e972ad.mp4

**Comment by subhangi2731** [comment]
@kothariji please merge my pr I have done everything loader and modal

**Review by kothariji — APPROVED** [review]
LGTM 🔥

**Comment by subhangi2731** [comment]
thanks @kothariji can u pleasw add the level tag and labels

**Comment by kothariji** [comment]
@subhangi2731 Done 🚀 , please check !

**Pull request merged**
