### PR TITLE
🚀[Feat]: Reconnect user on refresh issue #69

### PR DESCRIPTION
**Pull request by simran2607**
On refresh user is reconnected back to the same room. Code persist.

### CODE REVIEW

**Review by kothariji — COMMENTED** [review]
@simran2607 great work 🔥 
It's Working Perfectly. 
But I am confused about some of the functions, that why you add those. So it would be great if you can add comments so that we all can understand the code in a better way.

Also there are merge conflicts so please resolve those 🙌

**Comment by simran2607** [comment]
> @simran2607 great work 🔥
> It's Working Perfectly.
> But I am confused about some of the functions, that why you add those. So it would be great if you can add comments so that we all can understand the code in a better way.
> 
> Also there are merge conflicts so please resolve those 🙌

Thank you! Surely I will add comments to all my changes. 🙌

**Comment by simran2607** [comment]
> > @simran2607 great work 🔥
> > It's Working Perfectly.
> > But I am confused about some of the functions, that why you add those. So it would be great if you can add comments so that we all can understand the code in a better way.
> > Also there are merge conflicts so please resolve those 🙌
> 
> Thank you! Surely I will add comments to all my changes. 🙌

Resolved the conflicts and added comments. Pls do review it. And let me know for any changes

**Review by kothariji — APPROVED** [review]
@simran2607 Thank you so much for the contributions 🔥 ⭐ 

Keep Contributing 🚀

**Pull request merged**
