### PR TITLE
Fixed Issue : Room only shows updated content after first change

### PR DESCRIPTION
**Pull request by Shubham-Kumar-2000**
Solved Issue : #12

### CODE REVIEW

**Review by kothariji — CHANGES_REQUESTED** [review]
Hey @Shubham-Kumar-2000 , this LGTM 🚀 
But can you please add comments to the code, so that it would be better for others to understand the code easily

**Comment by Shubham-Kumar-2000** [comment]
Ya Sure.

**Comment by kothariji** [comment]
> Ya Sure.

Great

**Comment by Shubham-Kumar-2000** [comment]
@kothariji  I have added comments for better understandability.

**Review by kothariji — APPROVED** [review]
Approved

**Pull request merged**
