### PR TITLE
🚀[Feat]: Add Default Code for each Language

### LINKED ISSUE #16: Add Default Code for each Language
PS: I would like to work on this issue.

### PR DESCRIPTION
**Pull request by jainaayush01**
Issue #16

### CODE REVIEW

**Comment by jainaayush01** [comment]
Should I make a new PR and close this one Because I didn't saw the Contributing guidelines and haven't added a heading and description of commits in a proper way btw its self explanatory not much explanation is there but still let me know if there is something I need to do. Thanks for waiting!

**Comment by Vishv07** [comment]
It would be better if you can implement the logic that will change the code in the editor when you select the diff language. 

This would be totally fine too if you end up here.

**Review by kothariji — CHANGES_REQUESTED** [review]
Hi @jainaayush01 thanks for creating the PR.

But there is a minor change, consider the scenario below.

Scenario - Consider there are two users working in C++, and suddenly one of them changes a language to JAVA, then the entire code is changed(i.e. default code of JAVA is displayed) affecting both the user. So this should not happen right. 
Solution (I am able to think of) - once a user starts coding, even if he changes language, the current code should not wipe off, as it will affect another users right!.

Also currently whenever a new user joins, the entire code is replaced with the default code. So this is a bug we need to fix.

Thanks! 🚩

**Comment by Vishv07** [comment]
We gotta implement cache layer sooner or later @kothariji

**Comment by kothariji** [comment]
> We gotta implement cache layer sooner or later @kothariji

I swear, localStorage will be soon our best friend 😆

**Comment by jainaayush01** [comment]
Also when a user is already in the room if the Language is changed in one Room it is not reflected in the other.

The solution I am thinking of is: Keeping the code for each particular language in storage(or database) and if the user wants to come back to that particular language same code is visible. and when a new user joins a room the same settings of that room are displayed and not when we create a new room and also if the language is changed it also changes in another room (similar to code).

Thanks for highlighting all the bugs  🚩

**Comment by jainaayush01** [comment]
I missed that scenario @kothariji.

**Comment by kothariji** [comment]
> Also when a user is already in the room if the Language is changed in one Room it is not reflected in the other.
> 
> The solution I am thinking of is: Keeping the code for each particular language in storage(or database) and if the user wants to come back to that particular language same code is visible. and when a new user joins a room the same settings of that room are displayed and not when we create a new room and also if the language is changed it also changes in another room (similar to code).
> 
> Thanks for highlighting all the bugs 🚩

Yes, that too! 🙌

**Comment by Vishv07** [comment]
Error while executing java code.  Kindly check

**Comment by jainaayush01** [comment]
image
why is this error coming on my localhost

**Comment by kothariji** [comment]
> image
> why is this error coming on my localhost

This might be because you local host may not be connected with backend, please check again

**Comment by jainaayush01** [comment]
> > image
> > why is this error coming on my localhost
> 
> This might be because you local host may not be connected with backend, please check again

i don't understand what you are saying.
Like i have my server up and running on 4000 and my client is running on 3000.
is there a .env file that i have to setup?
and also i am seeing that this request is made to :3000

**Comment by jainaayush01** [comment]
and also if anyone can help me how to solve this issue will be a great help (above comments).

**Comment by kothariji** [comment]
Hi @jainaayush01, as REDUX is implemented in our code, now we can think over this PR. Please let me know your thought on this

**Comment by jainaayush01** [comment]
Yeah, I was thinking of this PR yesterday.
Now when I saw this from different perspectives, I think it isn't a good idea to change the code each time user changes the language because the thing is might be a user when started might have not noticed and have written code in java but when he changes language at that time his code will disappear, of course, he can get that by CTRL+Z but doesn't make any sense.

However, if we need to make this type of change, we can go like adding a button to add default language code for that particular language.
Please let me know your viewpoints.

**Comment by jainaayush01** [comment]
By the way, Redux's work is done amazingly.

**Comment by kothariji** [comment]
> Yeah, I was thinking of this PR yesterday.
> Now when I saw this from different perspectives, I think it isn't a good idea to change the code each time user changes the language because the thing is might be a user when started might have not noticed and have written code in java but when he changes language at that time his code will disappear, of course, he can get that by CTRL+Z but doesn't make any sense.
> 
> However, if we need to make this type of change, we can go like adding a button to add default language code for that particular language.
> Please let me know your viewpoints.

@jainaayush01, yeah I do agree with your point. 
But we can have an alternative for that...what if we can have 19 different codes for 19 different languages. And when I am working in C++ only code of C++ will change, and if I switch to python , then python default code will be shown, and then if I again  go back to cpp, then we get from where we left.

But I can smell a bug in this implementation.
Imagine a case when we both are working on a code in C++, then if I change language to python, then python default code will be shown, for both of us...and this will create a mess 😄 

What's your take on this !!

**Comment by jainaayush01** [comment]
It will be a mess because if we are working on a team we ain't gonna change the language frequently. 

And we should let the each member decide which language they want to run and not change it if one of member changes the language. In Short letting members decide what they want to do.

**Comment by jainaayush01** [comment]
Yes and only the user which has changed the language lastly will only be applicable to restore that code as CtRl +Z works for that person only

**Comment by kothariji** [comment]
Correct, so I think we should keep this PR on hold, and then If we get and good solution to this issue, we'll work on it. 🙌 

Anyways, thank you so much working on this 🚀

**Comment by kothariji** [comment]
> By the way, Redux's work is done amazingly.

Yes, honestly @Vishv07 did tremendous work.

**Comment by jainaayush01** [comment]
Yup couldn't agree more!

**Comment by Vishv07** [comment]
🥂 @kothariji @jainaayush01

**Pull request closed without merging**
