### PR TITLE
🚀 [FEAT: ] Download code feature

### PR DESCRIPTION
**Pull request by amaan-ahmad**
The feature has been tested successfully for all the currently supported languages

This PR includes:
- addition of a utility function that returns the extension name for a requested language code
- feature to allow users to download the code conveniently. 

Closes: #96 

**Screenshot**

image

### CODE REVIEW

**Review by kothariji — COMMENTED** [review]
@amaan-ahmad thanks for the PR 🔥 
Things are working great. 🙌 ⭐ 

The only thing for which I am concerned with is UI
image
 The footer of syntax editor is too poky..All buttons are tightly filled, which is a symbol of Bad UI.
 Can you suggest any alternatives for that.
 
 Also any suggestions for the same - @Vishv07 @Priyankcoder @jainaayush01 @AmeyaJain-25 @AyushShri

**Comment by jainaayush01** [comment]
I think we can go with only buttons and on hover we can describe that this options to upload, copy to clipboard, download.
And we can keep the run as it is

**Comment by amaan-ahmad** [comment]
Yes, @kothariji I agree with what you said, the UI does seem too crowded at the bottom. also, I agree with @jainaayush01 opinion on it. We can remove the text and let alone icons sit there.

Another choice would be adding something like this  image

to have an extended list of options available for users to choose from.

**Comment by AmeyaJain-25** [comment]
Yes @kothariji ,
I think as @jainaayush01 said, that we can show the icons and on hovering we can give the description or title.
One more suggestion is that the enable auto-complete is taking a lot of space, which is not needed.
So, I think if we can shift of make it smaller which can give space at bottom and make it more clean.

Another way is to use a Modal/Dialog or PopUp to give options to Copy, Download, etc.

**Comment by kothariji** [comment]
Yes exaclty, I feel the same @jainaayush01 @amaan-ahmad @AmeyaJain-25, actually, I think an Issue thread would be a much better place to talk on this 😄. So I have created the issue #118 , and we all can discuss it there

**Comment by kothariji** [comment]
For now, @amaan-ahmad , can you please change thing accordingly
1. remove Enable from `Enable Auto-complete`  because its understandable, no need of enale keyword.
image
2. Can you please add [Button Group](https://material-ui.com/components/button-group/) of Maerial UI for upload and download code...with just symbols. No text.. Just two symbols in button group format
 will work. We will work on it in issue #118 
 
image

We can merge this PR, once this points are validated

**Comment by Vishv07** [comment]
I think as of now we can just put a download icon there no need to put the whole button than an icon into the button to make some space.  or maybe just icons for all the three options except RUN.

**Comment by amaan-ahmad** [comment]
Hey @kothariji 
Yes I understood the changes that are to be made, my suggestion is let's do further discussion in issue #118 and merge this PR

**Comment by kothariji** [comment]
> Hey @kothariji
> Yes I understood the changes that are to be made, my suggestion is let's do further discussion in issue #118 and merge this PR

Sure  @amaan-ahmad, but if I merge this PR  now, it will move to production, and the syntaxeditor footer won't look good. So if possible can you please do 2 quick changes.
1 .remove Enable from Enable Auto-complete.
2. Please add Button Group of Material UI for upload and download code...with just symbols. 

So that it will work for now. Because we are not sure how much time #118 will take to resolve Right ?.

**Comment by amaan-ahmad** [comment]
Okay @kothariji 

image

How about this?

**Review by kothariji — APPROVED** [review]
Thanks for the contributions 🔥 

Keep contributing 🚀

**Pull request merged**
