### PR TITLE
Added a Button to leave

### PR DESCRIPTION
**Pull request by Devenkapoor7303**
Added a leave button on the navbar with red color @kothariji 

Navbar

### CODE REVIEW

**Review by kothariji — CHANGES_REQUESTED** [review]
Hi @Devenkapoor7303, UI is good, but the button is not working, it should redirect a person to the home page as expected, but it's nonfunctional, the reason is there is no onClick method on the button. Also, you can achieve the same by the Link component provided by react-router-dom. 
For reference, you can view the temporarily deployed website https://syntaxmeets-git-fork-devenkapoor7303-master-kothariji.vercel.app. Its not redirecting me to home page.

**Comment by Devenkapoor7303** [comment]
Okay I will make changes in that and add an event handler to that button

**Comment by kothariji** [comment]
> Okay I will make changes in that and add an event handler to that button

Great 🚀

**Comment by Devenkapoor7303** [comment]
@kothariji I have added the functionality so that it will be redirected to the home page

**Review by kothariji — APPROVED** [review]
Great 🚀

**Pull request merged**
