### PR TITLE
⚒️[Fix]: Scrollbar Customized

### PR DESCRIPTION
**Pull request by ShubhamSj07**
Scrollbar-Styles Added!
Also noticed one issue ,
When we clicked on participants , we see two scrollbars 
Pointed-issue

one scrollbar would do work for scrolling participants list , so i had removed overflow-y: scroll property!
Issue-Fixed

### CODE REVIEW

**Comment by ShubhamSj07** [comment]
@kothariji , pls review this

**Review by kothariji — APPROVED** [review]
@ShubhamSj07  Thanks for the contributions 🚀

Keep Contributing 🔥

**Comment by amaan-ahmad** [comment]
hey @ShubhamSj07 just saw the updated scrollbar on the web app, It's really awesome man💯🔥🔥

**Comment by ShubhamSj07** [comment]
> hey @ShubhamSj07 just saw the updated scrollbar on the web app, It's really awesome man💯🔥🔥

@amaan-ahmad , thanks🙌🏻

**Comment by kothariji** [comment]
> hey @ShubhamSj07 just saw the updated scrollbar on the web app, It's really awesome man💯🔥🔥

Honestly @ShubhamSj07, tremendous work, looks stunning  🔥 🥇

**Comment by ShubhamSj07** [comment]
> > hey @ShubhamSj07 just saw the updated scrollbar on the web app, It's really awesome man💯🔥🔥
> 
> Honestly @ShubhamSj07, tremendous work, looks stunning 🔥 🥇

@kothariji , tysm🙌🏻

**Pull request merged**
