### PR TITLE
[Feat]: Improved chat message UI

### PR DESCRIPTION
**Pull request by amaan-ahmad**
As referring to issue #80 

I stored the name of the user in local storage whenever they create/join the room.
and then compare it with `data.name` in `ChatMessage.js` as needed to do CSS-in-JS styling.

The output looks like this 👇

image

### CODE REVIEW

**Comment by kothariji** [comment]
Great work @amaan-ahmad 🔥 , 
But can you please resolve PR #78 so that we can review this PR

**Comment by amaan-ahmad** [comment]
Thanks @kothariji 
also, I have now resolved PR #78 and hopefully didn't create another conflict 😅
Looking forward to getting reviewed on the latest changes as well as this PR.

**Comment by kothariji** [comment]
> Thanks @kothariji
> also, I have now resolved PR #78 and hopefully didn't create another conflict 😅
> Looking forward to getting reviewed on the latest changes as well as this PR.

Sure we will analyse your PR, and will soon let you know 🙌

**Comment by kothariji** [comment]
> Thanks @kothariji
> also, I have now resolved PR #78 and hopefully didn't create another conflict 😅
> Looking forward to getting reviewed on the latest changes as well as this PR.

@amaan-ahmad can you please pull the updated code from original repo, and again commit the changes, as in this PR previous changes are visible

**Comment by amaan-ahmad** [comment]
Ok @kothariji 
I have now pulled the latest changes from the original repo and pushed them. no conflicts occurred. kindly review.

**Review by kothariji — APPROVED** [review]
Great 🚀 
This looks really nice 🔥

Keep Contributing, 🙌

**Pull request merged**
