### PR TITLE
Improve security of website  [#75 -fixed]

### PR DESCRIPTION
**Pull request by krishna-y2000**
I have applied http headers using helmet which will protect  against DDOS attack and applied the rate limiter for 100 request in every hour which will not overload the site.
Review this and if correct then please merge it.
Thanks.

### CODE REVIEW

**Comment by Vishv07** [comment]
As of now! It seems good. Should work fine as we have very low traffic. We will configure more balancing stuff when our MVP is ready.
LGTM🚀

**Comment by krishna-y2000** [comment]
@Vishv07 yes, you can implement balancing stuff in future but please merge this pr as i have worked on this . It is good for me as well as for you . Thanks.

**Comment by krishna-y2000** [comment]
@Vishv07 yes, you can implement balancing stuff in future but please merge this pr as i have worked on this . It is good for me as well as for you.Thanks .

**Comment by kothariji** [comment]
> @Vishv07 yes, you can implement balancing stuff in future but please merge this pr as i have worked on this . It is good for me as well as for you.Thanks .

Yes @krishna-y2000 , our team is reviewing it, and soon we will merge it once all checks are ticked ✅

**Review by kothariji — CHANGES_REQUESTED** [review]
Hi @krishna-y2000,

I tried testing this PR locally, but its not working, the socket connection is not established between two peers. Please try running it from your end.

Aslo if no changes are there in the frontend, then please don't commit the frontend's package.json and package-lock.json in the PR

**Comment by Vishv07** [comment]
@kothariji preview was working I guess when I checked in the morning. does it have a problem with localhost only?

**Comment by kothariji** [comment]
> @kothariji preview was working I guess when I checked in the morning. does it have a problem with localhost only?

No, actually that preview only works for the frontend and not the backend, so if there are any changes in backend, we have to test it locally 🙌

**Comment by krishna-y2000** [comment]
@kothariji  , i have modified the code . As there was only one small error so i have changed this on github .  It was due to rate limiter was added during connection . I have removed it and tested this on local system. Please verify it.

**Comment by Vishv07** [comment]
> > @kothariji preview was working I guess when I checked in the morning. does it have a problem with localhost only?
> 
> No, actually that preview only works for the frontend and not the backend, so if there are any changes in backend, we have to test it locally 🙌

Oh, gotcha. did you use Heroku PR deployment to check?

**Comment by kothariji** [comment]
> > > @kothariji preview was working I guess when I checked in the morning. does it have a problem with localhost only?
> > 
> > 
> > No, actually that preview only works for the frontend and not the backend, so if there are any changes in backend, we have to test it locally 🙌
> 
> Oh, gotcha. did you use Heroku PR deployment to check?

Currently not, soon trying to implement a pipeline review for the same.

**Review by kothariji — APPROVED** [review]
@krishna-y2000 Thank you for your contributions. 🚀 

Keep Contributing 🔥 🔥

**Pull request merged**
